Develop
flojoy-io/studio pull request #391
Opened 2023-05-16 01:29 UTC by jackparmer

2023-05-16 01:46 UTC, itsjoeoui requested changes

2023-05-16 01:46 UTC, itsjoeoui commented on requirements.txt
> +ticlib
We should probably pin this as well!

2023-05-16 01:46 UTC, itsjoeoui commented on src/feature/common/Sidebar/Sidebar.tsx
> +        if (node["child"] != null && !("key" in node)) {
Looks like this should be `!==` instead? @izi-on

2023-05-16 01:46 UTC, itsjoeoui commented on src/feature/common/Sidebar/Sidebar.tsx
> +  const renderSection = (textInput: string, node: Node, depth: number) => {
@izi-on Can you also add the return type of this function please

2023-05-16 01:46 UTC, itsjoeoui commented on src/feature/common/Sidebar/Sidebar.tsx
> +      if (node["child"] != null && !("key" in node)) {
Should be `!==`, there are a couple `==` below that should be changed as well

2023-05-16 01:46 UTC, itsjoeoui commented on src/feature/common/defaultPlotLayout.ts
> +  const plotFeatureColor = theme === "light" ? "#282c34" : "#fff";
We may want to use the theme we defined instead of hard-coding

2023-05-16 19:51 UTC, itsjoeoui submitted a review, later dismissed

2023-05-16 20:12 UTC, smahmed776 requested changes

2023-05-16 20:12 UTC, smahmed776 commented on requirements.txt
> +ticlib==0.2.2
This is a node-specific dependency and shouldn't be here.

2023-05-24 00:57 UTC, smahmed776 approved these changes

2023-05-24 00:59 UTC, merged