Updated react modals to mantine
flojoy-io/studio pull request #416
Opened 2023-05-17 20:43 UTC by Jin1L

- Updated to mantine style
- format

2023-05-17 20:49 UTC, itsjoeoui approved these changes
lgtm

2023-05-17 20:53 UTC, smahmed776 requested changes
Looks good, some cosmetic changes were requested.

2023-05-17 20:53 UTC, smahmed776 commented on src/feature/flow_chart_panel/views/NodeModal.tsx
> +import { useState, useEffect } from "react";
I think this import is unused.

2023-05-18 16:21 UTC, smahmed776 commented on src/__tests__/feature/flow_chart_panel/views/NodeModal.test.tsx
> +// jest.mock("@mantine/core", () => {
Can we just get rid of unnecessary comments, Please?

2023-05-18 16:22 UTC, smahmed776 commented on src/__tests__/feature/flow_chart_panel/views/NodeModal.test.tsx
> +  //modalStyles: {},
I think we shouldn't keep any unnecessary comments in code.

2023-05-18 16:23 UTC, smahmed776 requested changes
Looks good, I recommend removing unnecessary comments.

2023-05-18 16:47 UTC, smahmed776 approved these changes
LGTM

2023-05-18 16:48 UTC, merged