Get Electron working again
flojoy-io/studio pull request #588
Opened 2023-06-15 16:28 UTC by itsjoeoui

2023-06-15 16:30 UTC, yassine-moumen commented
## To access Flojoy-studio build from this pull request, you can use the following URLs: 

Windows installation: http://588_windows.flojoy-test.com:3000 
Linux installation: http://588_linux.flojoy-test.com:3000 

Please note that it may take a few minutes for the instance to start up, so please be patient. 

It is important to know that the instance will automatically shut down after 4 hours to conserve resources. If you wish to start the instance again after it shuts down (or restart it to pickup new changes), you can use this API : 

Windows: https://kgpsoscpc4q52d4mtwuu7jhvie0qdiso.lambda-url.us-east-1.on.aws/start_instance?instance_id=i-0dc1117403883af85&domain=588_windows 

Linux: https://kgpsoscpc4q52d4mtwuu7jhvie0qdiso.lambda-url.us-east-1.on.aws/start_instance?instance_id=i-0334f1ade88272066&domain=588_linux

2023-06-21 18:44 UTC, dev-nested approved these changes

2023-06-21 19:57 UTC, smahmed776 requested changes
Looks good

2023-06-21 19:57 UTC, smahmed776 commented on electron/main/index.ts
> +    autoHideMenuBar: true,
This should be false for dev mode for debugging purpose and can set to true for packaged version IMO.

2023-07-20 23:29 UTC, smahmed776 approved these changes
looks good

2023-07-20 23:30 UTC, merged