Cypress code coverage
flojoy-io/studio pull request #623
Opened 2023-06-23 20:42 UTC by Jin1L

2023-06-23 20:44 UTC, yassine-moumen commented
## To access Flojoy-studio build from this pull request, you can use the following URLs: 

Windows installation: http://623_windows.flojoy-test.com:3000 
Linux installation: http://623_linux.flojoy-test.com:3000 

Please note that it may take a few minutes for the instance to start up, so please be patient. 

It is important to know that the instance will automatically shut down after 4 hours to conserve resources. If you wish to start the instance again after it shuts down (or restart it to pickup new changes), you can use this API : 

Windows: https://kgpsoscpc4q52d4mtwuu7jhvie0qdiso.lambda-url.us-east-1.on.aws/start_instance?instance_id=i-0a0a9481ab469d5c3&domain=623_windows 

Linux: https://kgpsoscpc4q52d4mtwuu7jhvie0qdiso.lambda-url.us-east-1.on.aws/start_instance?instance_id=i-04e1ee0e820d5361f&domain=623_linux

2023-07-03 19:59 UTC, scorinaldi requested changes
This mostly looks good, thanks for your hard work here! There are a few remaining issues, which I'll list below:

- Please write a thorough Top Comment for this PR. If you had to review this change in a year, what would you present to yourself to make it easy as possible to have them understand the change? to see an outline of the solution in the PR top comment. How did you solve this problem? What are notable pieces of code, etc. 
- Please write an intro guide in Notion to help folks understand how to write FE tests. You spent the time and effort to learn this from scratch, your mission is to make sure **no one ever has to do that again**. We want everyone to write front FE tests!!
- Please add a 1-2 sentence description in each .cy.ts test file to say what the test does
- Please run lint on this.

(Note to other reviewers that the tsx changes are just 1 liners, just identifying the components to the testing framework)

2023-07-03 19:59 UTC, scorinaldi commented on package.json
> +      "src/feature/flow_chart_panel/components/nodes/PieChart.tsx",
Ideally we want this exclude list to be small. Please go grep through this list and confirm that none of the files/classes here are being used in prod. If there's merged (non-test) code that's not being used in in prod that's not great either, so we should file an issue to follow up later.

If you wind up un-commenting some stuff and the coverage falls below 80% that's ok. We just need to make a follow up list so we know what tests to write in the future.

2023-07-03 19:59 UTC, scorinaldi commented on src/__tests__/feature/flow_chart_panel/__snapshots__/FlowChartTabView.test.tsx.snap
> -                style="display: flex; gap: 10.77px;"
These are auto-generated , we don't know why it was removed.

2023-07-05 15:21 UTC, scorinaldi approved these changes
Comments and top comment look great! Thanks for all your hard work here.

LGTM

2023-07-05 15:34 UTC, merged