Working on the API modal
flojoy-io/studio pull request #660
Opened 2023-07-06 21:59 UTC by Jin1L

2023-07-06 22:01 UTC, yassine-moumen commented
## To access Flojoy-studio build from this pull request, you can use the following URLs: 

Windows installation: http://660_windows.flojoy-test.com:3000 
Linux installation: http://660_linux.flojoy-test.com:3000 

Please note that it may take a few minutes for the instance to start up, so please be patient. 

It is important to know that the instance will automatically shut down after 4 hours to conserve resources. If you wish to start the instance again after it shuts down (or restart it to pickup new changes), you can use this API : 

Windows: https://kgpsoscpc4q52d4mtwuu7jhvie0qdiso.lambda-url.us-east-1.on.aws/start_instance?instance_id=i-0d7256f30cf567f35&domain=660_windows 

Linux: https://kgpsoscpc4q52d4mtwuu7jhvie0qdiso.lambda-url.us-east-1.on.aws/start_instance?instance_id=i-0bcf8fdeded1d4f87&domain=660_linux

2023-07-12 23:51 UTC, JeffDotPng requested changes

2023-07-12 23:51 UTC, JeffDotPng commented on src/feature/flow_chart_panel/views/APIKeyModal.tsx
> +  const { s3AccessKey, setS3AccessKey, s3SecretKey, setS3SecretKey } =
duplicate hook call?

2023-07-12 23:51 UTC, JeffDotPng commented on src/services/FlowChartServices.ts
> +        title: "Successful!",
The 3 functions to send the post request are almost exactly the same except for the endpoint they query, please refactor

2023-07-13 19:53 UTC, JeffDotPng requested changes

2023-07-13 19:53 UTC, JeffDotPng commented on src/feature/flow_chart_panel/views/APIKeyModal.tsx
> +  } = useFlowChartState();
still duplicate hook call

2023-07-13 19:53 UTC, JeffDotPng commented on src/services/FlowChartServices.ts
> +export const sendApiKeyToDjango = async (apiKey: string, apiFor: string) => {
```typescript
export const postApiKey = async (endpoint: string, body: object) => {
  try {
    const response = await fetch(`${API_URI}/api/${endpoint}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    if (response.ok) {
      const responseData = await response.json();
      notifications.update({
        id: "set-api-key",
        title: "Successful!",
        message: "Successfully set key",
        autoClose: 5000,
      });
    } else {
      notifications.update({
        id: "set-api-key",
        title: "Failed!",
        message: "Failed to set key",
        autoClose: 5000,
      });
    }
  } catch (error) {
    notifications.update({
      id: "set-api-key",
      title: "Failed!",
      message: "Failed to set key",
      autoClose: 5000,
    });
  }
};

export const postCloudApiKey = async (key: string) => {
  await postApiKey("set-cloud-key", { key });
};

export const postS3Key = async (
  s3Name: string,
  s3AccessKey: string,
  s3SecretKey: string
) => {
  await postApiKey("set-s3-key", {
    name: s3Name,
    accessKey: s3AccessKey,
    secretKey: s3SecretKey,
  });
};

export const postOpenAIKey = async (key: string) => {
  await postApiKey("set-openai-key", { key });
};
```

2023-07-13 21:22 UTC, itsjoeoui commented on src/services/FlowChartServices.ts
> +export const sendApiKeyToDjango = async (body: object, endpoint: string) => {
type this object

2023-07-13 22:17 UTC, JeffDotPng approved these changes

2023-07-13 22:18 UTC, merged